-- ==============================================================================
-- MIGRATION: Advertising Monitoring Schema V2
-- ==============================================================================

-- 1. PORTAL_PAGES
CREATE TABLE IF NOT EXISTS public.portal_pages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portal_id BIGINT REFERENCES public.portals(id) ON DELETE CASCADE,
    url TEXT NOT NULL,
    canonical_url TEXT,
    title TEXT,
    page_type TEXT,
    depth INTEGER,
    discovery_source TEXT,
    anchor_text TEXT,
    advertising_opportunity_score NUMERIC,
    commercial_relevance_score NUMERIC,
    monitoring_priority_score NUMERIC,
    is_monitored BOOLEAN DEFAULT FALSE,
    is_excluded BOOLEAN DEFAULT FALSE,
    selection_reason TEXT,
    last_discovered_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'uq_portal_pages_url'
    ) THEN
        ALTER TABLE public.portal_pages ADD CONSTRAINT uq_portal_pages_url UNIQUE (portal_id, url);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_portal_pages_portal_id ON public.portal_pages(portal_id);

-- 2. ADVERTISING_DETECTION_EVENTS
CREATE TABLE IF NOT EXISTS public.advertising_detection_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evidence_id BIGINT REFERENCES public.advertising_evidence(id) ON DELETE CASCADE,
    portal_id BIGINT REFERENCES public.portals(id) ON DELETE CASCADE,
    portal_scan_id BIGINT REFERENCES public.portal_scans(id) ON DELETE CASCADE,
    source_page_url TEXT,
    landing_url TEXT,
    detection_method TEXT CHECK (
      detection_method IN (
        'DOM_CLASS',
        'IFRAME_SRC',
        'EXTERNAL_IMAGE_LINK',
        'TEXT_DISCLOSURE',
        'EXTERNAL_PROMOTION'
      )
    ),
    detection_signals_jsonb JSONB,
    detected_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_adv_events_evidence_id ON public.advertising_detection_events(evidence_id);
CREATE INDEX IF NOT EXISTS idx_adv_events_portal_id ON public.advertising_detection_events(portal_id);
CREATE INDEX IF NOT EXISTS idx_adv_events_scan_id ON public.advertising_detection_events(portal_scan_id);
CREATE INDEX IF NOT EXISTS idx_adv_events_detected_at ON public.advertising_detection_events(detected_at);

-- 3. PORTAL_SCANS
ALTER TABLE public.portal_scans 
    ADD COLUMN IF NOT EXISTS rendered_pages_count INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS visual_candidates_count INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS verified_ads_count INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS rejected_ads_count INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS ocr_processed_count INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS gemini_calls_count INTEGER DEFAULT 0;

-- 4. ADVERTISING_EVIDENCE
ALTER TABLE public.advertising_evidence
    ADD COLUMN IF NOT EXISTS evidence_fingerprint TEXT,
    ADD COLUMN IF NOT EXISTS last_seen_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    ADD COLUMN IF NOT EXISTS detection_count INTEGER DEFAULT 1,
    ADD COLUMN IF NOT EXISTS verification_confidence NUMERIC,
    ADD COLUMN IF NOT EXISTS ai_confidence NUMERIC,
    ADD COLUMN IF NOT EXISTS evidence_status TEXT,
    ADD COLUMN IF NOT EXISTS page_screenshot_url TEXT,
    ADD COLUMN IF NOT EXISTS ad_screenshot_url TEXT,
    ADD COLUMN IF NOT EXISTS ad_screenshot_storage_path TEXT,
    ADD COLUMN IF NOT EXISTS page_screenshot_storage_path TEXT,
    ADD COLUMN IF NOT EXISTS ad_bbox_jsonb JSONB,
    ADD COLUMN IF NOT EXISTS ocr_confidence NUMERIC,
    ADD COLUMN IF NOT EXISTS visual_fingerprint TEXT,
    ADD COLUMN IF NOT EXISTS gemini_analysis_jsonb JSONB,
    ADD COLUMN IF NOT EXISTS render_status TEXT,
    ADD COLUMN IF NOT EXISTS detection_confidence NUMERIC,
    ADD COLUMN IF NOT EXISTS identity_confidence NUMERIC,
    ADD COLUMN IF NOT EXISTS ad_image_url TEXT,
    ADD COLUMN IF NOT EXISTS image_hash TEXT,
    ADD COLUMN IF NOT EXISTS image_width INTEGER,
    ADD COLUMN IF NOT EXISTS image_height INTEGER,
    ADD COLUMN IF NOT EXISTS banner_format TEXT,
    ADD COLUMN IF NOT EXISTS sponsor_disclosure TEXT,
    ADD COLUMN IF NOT EXISTS sponsor_text TEXT,
    ADD COLUMN IF NOT EXISTS article_title TEXT,
    ADD COLUMN IF NOT EXISTS article_excerpt TEXT,
    ADD COLUMN IF NOT EXISTS first_seen_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();

-- 5. EVIDENCE FINGERPRINT
CREATE UNIQUE INDEX IF NOT EXISTS uq_adv_evidence_fingerprint 
ON public.advertising_evidence(evidence_fingerprint) 
WHERE evidence_fingerprint IS NOT NULL;

-- 6. RLS
ALTER TABLE public.portal_pages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.advertising_detection_events ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'portal_pages' AND policyname = 'portal_pages_select'
    ) THEN
        CREATE POLICY "portal_pages_select" ON public.portal_pages FOR SELECT TO authenticated USING (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'advertising_detection_events' AND policyname = 'adv_events_select'
    ) THEN
        CREATE POLICY "adv_events_select" ON public.advertising_detection_events FOR SELECT TO authenticated USING (true);
    END IF;
END $$;
